name: pyrotechnics
channels:
  - conda-forge
dependencies:
  - python=3.11
  - ipykernel
  - ryp
  - ca-certificates
  - openssl
  - r-mgcv
  - r-svglite
  - r-tinyplot
  - matplotlib
  - r-irkernel
  - certifi
  - scikit-learn
